@extends('admin')
@section('module')
   <table>
       <tr>
           <td>Hola</td>
       </tr>
       <tr>
           <td>Hola</td>
       </tr>
       <tr>
           <td>Hola</td>
       </tr>
   </table>
@endsection
